using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using static DepoOtomasyonV2.Classlarim.Yardimcilar;

namespace DepoOtomasyonV2
{
    public partial class CalisanForm : Form
    {
        public CalisanForm()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
        }

        private void CalisanForm_Load(object sender, EventArgs e)
        {

        }
        int? id =null;
        private void gridView1_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
            if (e.FocusedRowHandle < 0)
                return;

            // Hücre değerlerini almanın kısa yolu
            string GetString(string fieldName) => gridView1.GetFocusedRowCellValue(fieldName)?.ToString();

             id = int.Parse(GetString("Id"));
            string ad = GetString("Ad");
            string soyad = GetString("Soyad");
            string pozisyon = GetString("kullanicirols_Ad");
            string fotoYolu = GetString("Fotograf");
            string mail = GetString("Mail");

            labelAdSoyad.Text = $"{ad} {soyad}";
            labelDepartman.Text = pozisyon;
            maskedTel.Text = GetString("Telefon");
            linkMail.Text = mail;

            // Tarih kontrolü
            if (gridView1.GetFocusedRowCellValue("KayitTarihi") is DateTime tarih)
                dateTimePicker1.Value = tarih;
            else if (DateTime.TryParse(GetString("KayitTarihi"), out tarih))
                dateTimePicker1.Value = tarih;
            else
                dateTimePicker1.Value = DateTime.Now;

            // Fotoğraf yükleme
            LoadFoto(fotoYolu);
        }

        // Fotoğraf yükleme için ayrı metod
        private void LoadFoto(string fotoYolu)
        {
            if (!string.IsNullOrEmpty(fotoYolu) && File.Exists(fotoYolu))
            {
                try
                {
                    using (var stream = new MemoryStream(File.ReadAllBytes(fotoYolu)))
                    {
                        var img = Image.FromStream(stream);
                        pictureEdit1.Image = ResimBoyutlandir.Boyutlandir(img, pictureEdit1.Width, pictureEdit1.Height);
                    }

                    pictureEdit1.Properties.SizeMode = DevExpress.XtraEditors.Controls.PictureSizeMode.Stretch;
                }
                catch
                {
                    pictureEdit1.Image = null;
                }
            }
            else
            {
                pictureEdit1.Image = null;
            }
        }


        private void gridControl1_Click(object sender, EventArgs e)
        {

        }
        LogKayitlari logKayitlari;
        private void simpleButton1_Click(object sender, EventArgs e)
        {
            if (logKayitlari == null || logKayitlari.IsDisposed)
            {
                logKayitlari = new LogKayitlari(id);
                logKayitlari.MdiParent = this.MdiParent;  // Eğer bu kod alt formdan çalışıyorsa
                logKayitlari.Show();
            }
            else
            {
                logKayitlari.BringToFront();
                LogKayitlari git = new LogKayitlari(id);
            }
        }
    }
}
