using DepoOtomasyonV2.Classlarim;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace DepoOtomasyonV2
{
    public partial class FrmSatis : Form
    {
        public FrmSatis()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
        }

        private void FrmSatis_Load(object sender, EventArgs e)
        {
            gridControl1.DataSource = DataLister.Listele("SatilabilirListele");
        }

        private void tileView1_CustomUnboundColumnData(object sender, DevExpress.XtraGrid.Views.Base.CustomColumnDataEventArgs e)
        {
            // Yalnızca resim sütunumuz için çalıştır
            if (e.Column.FieldName == "colAyakkabiResmi" && e.IsGetData)
            {
                // 1. O anki satırdaki (karttaki) ResimYolu değerini al
                // 'ResimYolu', SQL sorgunuzdan gelen sütun adıdır.
                string resimYolu = (string)tileView1.GetRowCellValue(e.ListSourceRowIndex, "VarFoto");

                // 2. Resim yolu geçerliyse ve dosya varsa resmi belleğe yükle
                if (!string.IsNullOrEmpty(resimYolu) && System.IO.File.Exists(resimYolu))
                {
                    try
                    {
                        // Dosya kilitleme sorunlarını önlemek için resmi MemoryStream üzerinden yükle
                        using (var stream = new System.IO.MemoryStream(System.IO.File.ReadAllBytes(resimYolu)))
                        {
                            // e.Value'ye bellekteki resim nesnesini ata
                            e.Value = System.Drawing.Image.FromStream(stream);
                        }
                    }
                    catch
                    {
                        // Hata durumunda boş bırak
                        e.Value = null;
                    }
                }
            }
        }
    }
}
