using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace DepoOtomasyonV2
{
    public partial class LogKayitlari : Form
    {
        private int? calisanId;
        public LogKayitlari(int? calisanId = null)
        {
            InitializeComponent();
            this.calisanId = calisanId;
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
        }

        private void LogKayitlari_Load(object sender, EventArgs e)
        {
            // Logları yükle
            LoadLogs();
        }

        private void LoadLogs()
        {
            if (calisanId.HasValue)
            {
                // Sadece o çalışanın logları
                sqlDataSource1.Queries[0].Parameters["KullaniciId"].Value = calisanId.Value;
            }
            else
            {
                // Tüm loglar
                sqlDataSource1.Queries[0].Parameters["KullaniciId"].Value = DBNull.Value;
            }

            sqlDataSource1.Fill();
        }
    }
}
