using DevExpress.XtraGrid;
using DevExpress.XtraGrid.Views.Grid;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.IO;
using DevExpress.XtraGrid.Views.Base;

namespace DepoOtomasyonV2
{
    public partial class MalzemeListe : Form
    {
        public MalzemeListe()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource
            sqlDataSource1.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            gridView1.OptionsView.ShowAutoFilterRow = true;
            gridView1.OptionsView.ShowFooter = true;
            gridView1.OptionsView.ShowFooter = true;
            GridColumnSummaryItem summary = new GridColumnSummaryItem(
                DevExpress.Data.SummaryItemType.Sum, "StokMiktari", "Genel Stok: {0}");
            gridView1.Columns["StokMiktari"].Summary.Add(summary);


            // Grup bazında stok toplamı
            GridGroupSummaryItem groupSummary = new GridGroupSummaryItem();
            groupSummary.FieldName = "StokMiktari";  // Hangi alanın özetleneceği
            groupSummary.SummaryType = DevExpress.Data.SummaryItemType.Sum; // Toplama işlemi
            groupSummary.DisplayFormat = "Toplam Stok: {0}";
            groupSummary.ShowInGroupColumnFooter = gridView1.Columns["Stok"]; // Grupların altında stok sütununda göster
            gridView1.GroupSummary.Add(groupSummary);
        }
    }
}
