using DevExpress.XtraGrid;
using DevExpress.XtraGrid.Views.Grid;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace DepoOtomasyonV2
{
    public partial class UrunListesi : Form
    {
        public UrunListesi()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
        }

        private void repositoryItemButtonEdit1_Click(object sender, EventArgs e)
        {
            // GridControl'daki ilgili GridView'i alıyoruz
            var view = gridControl1.FocusedView as DevExpress.XtraGrid.Views.Grid.GridView;
            if (view == null) return;

            // Seçili satırın ID değerini alıyoruz (örnek: "UrunVaryasyonId" sütunu)
            var varyasyonId = view.GetFocusedRowCellValue("Id");

            if (varyasyonId != null)
            {
                MessageBox.Show("Seçilen varyasyon ID: " + varyasyonId.ToString(), "Bilgi", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
        }

        private void UrunListesi_Load(object sender, EventArgs e)
        {
            gridView1.OptionsView.ShowAutoFilterRow = true;
            gridView1.OptionsView.ShowFooter = true;
            gridView1.OptionsView.ShowFooter = true;
            GridColumnSummaryItem summary = new GridColumnSummaryItem(
                DevExpress.Data.SummaryItemType.Sum, "StokMiktari", "Genel Stok: {0}");
            gridView1.Columns["StokMiktari"].Summary.Add(summary);


            // Grup bazında stok toplamı
            GridGroupSummaryItem groupSummary = new GridGroupSummaryItem();
            groupSummary.FieldName = "StokMiktari";  // Hangi alanın özetleneceği
            groupSummary.SummaryType = DevExpress.Data.SummaryItemType.Sum; // Toplama işlemi
            groupSummary.DisplayFormat = "Toplam Stok: {0}";
            groupSummary.ShowInGroupColumnFooter = gridView1.Columns["Stok"]; // Grupların altında stok sütununda göster
            gridView1.GroupSummary.Add(groupSummary);
            gridView1.Columns["TahminiMaliyet"].DisplayFormat.FormatType = DevExpress.Utils.FormatType.Numeric;
            gridView1.Columns["TahminiMaliyet"].DisplayFormat.FormatString = "C2"; // TL formatı

            gridView1.Columns["EkFiyat"].DisplayFormat.FormatType = DevExpress.Utils.FormatType.Numeric;
            gridView1.Columns["EkFiyat"].DisplayFormat.FormatString = "C2"; // TL formatı


            //Başlıkları ve hücreleri ortalamak için
            gridView1.Appearance.Row.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center;
            gridView1.Appearance.HeaderPanel.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center;


            DevExpress.LookAndFeel.UserLookAndFeel.Default.SetSkinStyle("The Bezier");


            //Grup başlıkları düzenlemesi
            gridView1.Appearance.GroupRow.Font = new Font("Segoe UI", 9.5F, FontStyle.Bold);
            gridView1.Appearance.GroupRow.ForeColor = Color.DarkSlateGray;

        }

        private void gridView1_RowStyle_1(object sender, RowStyleEventArgs e)
        {
            GridView view = sender as GridView;

            if (e.RowHandle >= 0) // sadece veri satırları için
            {
                int stok;
                int minStok;

                // Stok ve Minimum Stok değerlerini al
                object stokValue = view.GetRowCellValue(e.RowHandle, "StokMiktari");
                object minStokValue = view.GetRowCellValue(e.RowHandle, "MinimumStok");

                if (stokValue != null && minStokValue != null
                    && int.TryParse(stokValue.ToString(), out stok)
                    && int.TryParse(minStokValue.ToString(), out minStok))
                {
                    if (stok < minStok)
                    {
                        e.Appearance.BackColor = Color.LightCoral; // Kırmızımsı
                        e.Appearance.ForeColor = Color.Black;
                    }
                    else
                    {
                        e.Appearance.BackColor = Color.LightGreen; // Yeşilimsi
                        e.Appearance.ForeColor = Color.Black;
                    }
                }
            }
        }

        private void gridView1_CustomUnboundColumnData_1(object sender, DevExpress.XtraGrid.Views.Base.CustomColumnDataEventArgs e)
        {
            GridView view = sender as GridView;

            if (e.Column.FieldName == "VarFoto" && e.IsGetData)
            {
                string path = view.GetRowCellValue(e.ListSourceRowIndex, "FotoYolu")?.ToString();

                if (!string.IsNullOrEmpty(path) && File.Exists(path))
                {
                    using (var temp = Image.FromFile(path))
                    {
                        e.Value = new Bitmap(temp); // GridView’e kopya resmi atıyoruz
                    }
                }
                else
                {
                    e.Value = null; // Dosya yoksa hücre boş kalsın, NullText görünür
                }
            }
        }
    }
}

